services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
